// movie_rest.go — movie rest: starts a local HTTP server for the library API
package cmd

import (
	"encoding/json"
	"fmt"
	"html/template"
	"net/http"
	"os"
	"os/exec"
	"runtime"
	"strconv"
	"strings"

	"github.com/spf13/cobra"

	"github.com/alimtvnetwork/movie-cli-v3/db"
	"github.com/alimtvnetwork/movie-cli-v3/errlog"
	"github.com/alimtvnetwork/movie-cli-v3/templates"
)

var restPort int
var restOpen bool

var movieRestCmd = &cobra.Command{
	Use:   "rest",
	Short: "Start a local REST API server for the library",
	Long: `Starts a lightweight HTTP server that exposes your movie library
via REST endpoints. The HTML report generated by 'movie scan' can
communicate with this server for interactive features.

Default port: 8086. Override with --port.

Endpoints:
  GET    /api/media              List all media
  GET    /api/media/{id}         Get a single media item
  DELETE /api/media/{id}         Remove a media item
  PATCH  /api/media/{id}         Update media fields (JSON body)
  GET    /api/media/{id}/similar TMDb recommendations
  PATCH  /api/media/{id}/watched Mark as watched
  GET    /api/tags               All tags with counts
  GET    /api/tags?media_id=N    Tags for a specific item
  POST   /api/tags               Add a tag (JSON: media_id, tag)
  DELETE /api/tags               Remove a tag (JSON: media_id, tag)
  GET    /api/stats              Library statistics

Examples:
  movie rest              Start on port 8086
  movie rest --port 9000  Start on port 9000
  movie rest --open       Start and open report in browser`,
	Run: runMovieRest,
}

func init() {
	movieRestCmd.Flags().IntVarP(&restPort, "port", "p", 8086,
		"port to listen on")
	movieRestCmd.Flags().BoolVar(&restOpen, "open", false,
		"open the HTML report in the default browser")
}

func runMovieRest(cmd *cobra.Command, args []string) {
	database, err := db.Open()
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Database error: %v\n", err)
		return
	}
	defer database.Close()

	mux := http.NewServeMux()

	// Serve live HTML report at root
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/" {
			http.NotFound(w, r)
			return
		}
		serveHTMLReport(w, database, restPort)
	})

	// Routes with sub-paths must be registered before the parent catch-all.
	mux.HandleFunc("/api/tags", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleTags(w, r, database)
	}))
	mux.HandleFunc("/api/media", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleListMedia(w, r, database)
	}))
	mux.HandleFunc("/api/media/", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		path := strings.TrimPrefix(r.URL.Path, "/api/media/")
		parts := strings.SplitN(path, "/", 2)
		if len(parts) == 2 {
			switch parts[1] {
			case "similar":
				handleSimilar(w, r, database)
				return
			case "watched":
				handleWatched(w, r, database)
				return
			}
		}
		handleMediaByID(w, r, database)
	}))
	mux.HandleFunc("/api/stats", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleStats(w, r, database)
	}))

	addr := fmt.Sprintf(":%d", restPort)
	url := fmt.Sprintf("http://localhost:%d", restPort)
	fmt.Printf("\n🚀 Movie CLI REST server running on %s\n", url)
	fmt.Println("   Press Ctrl+C to stop\n")
	fmt.Printf("   Endpoints:\n")
	fmt.Printf("     GET    /                       HTML library report\n")
	fmt.Printf("     GET    /api/media\n")
	fmt.Printf("     GET    /api/media/{id}\n")
	fmt.Printf("     DELETE /api/media/{id}\n")
	fmt.Printf("     PATCH  /api/media/{id}\n")
	fmt.Printf("     GET    /api/media/{id}/similar\n")
	fmt.Printf("     PATCH  /api/media/{id}/watched\n")
	fmt.Printf("     GET    /api/tags\n")
	fmt.Printf("     GET    /api/tags?media_id={id}\n")
	fmt.Printf("     POST   /api/tags\n")
	fmt.Printf("     DELETE /api/tags\n")
	fmt.Printf("     GET    /api/stats\n\n")

	if restOpen {
		go openBrowser(url)
	}

	if srvErr := http.ListenAndServe(addr, mux); srvErr != nil {
		fmt.Fprintf(os.Stderr, "❌ Server error: %v\n", srvErr)
	}
}

// openBrowser opens the given URL in the default browser.
func openBrowser(url string) {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", url)
	case "windows":
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", url)
	default:
		cmd = exec.Command("xdg-open", url)
	}
	if err := cmd.Start(); err != nil {
		fmt.Fprintf(os.Stderr, "⚠️  Could not open browser: %v\n", err)
	}
}

// corsWrap adds CORS headers so the HTML report can call the API from file:// or another port.
func corsWrap(handler http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PATCH, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		handler(w, r)
	}
}

func handleListMedia(w http.ResponseWriter, r *http.Request, database *db.DB) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	items, err := database.ListMedia(0, 10000)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, items)
}

func handleMediaByID(w http.ResponseWriter, r *http.Request, database *db.DB) {
	idStr := strings.TrimPrefix(r.URL.Path, "/api/media/")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		http.Error(w, "invalid id", http.StatusBadRequest)
		return
	}

	switch r.Method {
	case http.MethodGet:
		m, getErr := database.GetMediaByID(id)
		if getErr != nil {
			http.Error(w, "not found", http.StatusNotFound)
			return
		}
		writeJSON(w, m)

	case http.MethodDelete:
		if delErr := database.DeleteMedia(id); delErr != nil {
			http.Error(w, delErr.Error(), http.StatusInternalServerError)
			return
		}
		writeJSON(w, map[string]string{"status": "deleted"})

	case http.MethodPatch:
		var updates map[string]interface{}
		if decErr := json.NewDecoder(r.Body).Decode(&updates); decErr != nil {
			http.Error(w, "invalid json", http.StatusBadRequest)
			return
		}
		// For now, support updating basic fields via direct SQL
		for key, val := range updates {
			switch key {
			case "title", "genre", "director", "description", "tagline":
				database.Exec("UPDATE media SET "+key+" = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?", val, id)
			}
		}
		m, _ := database.GetMediaByID(id)
		writeJSON(w, m)

	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func handleStats(w http.ResponseWriter, r *http.Request, database *db.DB) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	total, _ := database.CountMedia("")
	movies, _ := database.CountMedia("movie")
	tv, _ := database.CountMedia("tv")
	writeJSON(w, map[string]int{"total": total, "movies": movies, "tv_shows": tv})
}

func writeJSON(w http.ResponseWriter, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(data); err != nil {
		fmt.Fprintf(os.Stderr, "⚠️  JSON encode error: %v\n", err)
	}
}

// serveHTMLReport renders the HTML report template with live data from the database.
func serveHTMLReport(w http.ResponseWriter, database *db.DB, port int) {
	tmplBytes, err := templates.FS.ReadFile("report.html")
	if err != nil {
		http.Error(w, "template not found", http.StatusInternalServerError)
		return
	}

	tmpl, parseErr := template.New("report").Parse(string(tmplBytes))
	if parseErr != nil {
		http.Error(w, "template parse error", http.StatusInternalServerError)
		return
	}

	items, listErr := database.ListMedia(0, 10000)
	if listErr != nil {
		http.Error(w, "database error", http.StatusInternalServerError)
		return
	}

	movies, tv := 0, 0
	reportItems := make([]htmlReportItem, 0, len(items))
	for _, m := range items {
		if m.Type == "movie" {
			movies++
		} else {
			tv++
		}
		var genres []string
		if m.Genre != "" {
			for _, g := range splitGenres(m.Genre) {
				genres = append(genres, g)
			}
		}
		reportItems = append(reportItems, htmlReportItem{
			ID:            m.ID,
			Title:         m.Title,
			Year:          m.Year,
			Type:          m.Type,
			Genre:         m.Genre,
			GenreList:     genres,
			Director:      m.Director,
			CastList:      m.CastList,
			Description:   m.Description,
			Tagline:       m.Tagline,
			TmdbRating:    m.TmdbRating,
			ImdbRating:    m.ImdbRating,
			Runtime:       m.Runtime,
			ThumbnailPath: m.ThumbnailPath,
		})
	}

	data := htmlReportData{
		ScannedFolder: "Library",
		ScannedAt:     "Live",
		TotalFiles:    len(items),
		Movies:        movies,
		TVShows:       tv,
		Port:          port,
		Items:         reportItems,
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := tmpl.Execute(w, data); err != nil {
		fmt.Fprintf(os.Stderr, "⚠️  Template render error: %v\n", err)
	}
}
