// movie_rest.go — movie rest: starts a local HTTP server for the library API
package cmd

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strconv"
	"strings"

	"github.com/spf13/cobra"

	"github.com/alimtvnetwork/movie-cli-v3/db"
)

var restPort int

var movieRestCmd = &cobra.Command{
	Use:   "rest",
	Short: "Start a local REST API server for the library",
	Long: `Starts a lightweight HTTP server that exposes your movie library
via REST endpoints. The HTML report generated by 'movie scan' can
communicate with this server for interactive features.

Default port: 8086. Override with --port.

Endpoints:
  GET    /api/media        List all media
  GET    /api/media/{id}   Get a single media item
  DELETE /api/media/{id}   Remove a media item
  PATCH  /api/media/{id}   Update media fields (JSON body)
  GET    /api/stats        Library statistics

Examples:
  movie rest              Start on port 8086
  movie rest --port 9000  Start on port 9000`,
	Run: runMovieRest,
}

func init() {
	movieRestCmd.Flags().IntVarP(&restPort, "port", "p", 8086,
		"port to listen on")
}

func runMovieRest(cmd *cobra.Command, args []string) {
	database, err := db.Open()
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Database error: %v\n", err)
		return
	}
	defer database.Close()

	mux := http.NewServeMux()
	mux.HandleFunc("/api/media", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleListMedia(w, r, database)
	}))
	mux.HandleFunc("/api/media/", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleMediaByID(w, r, database)
	}))
	mux.HandleFunc("/api/stats", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleStats(w, r, database)
	}))

	addr := fmt.Sprintf(":%d", restPort)
	fmt.Printf("\n🚀 Movie CLI REST server running on http://localhost:%d\n", restPort)
	fmt.Println("   Press Ctrl+C to stop\n")
	fmt.Printf("   Endpoints:\n")
	fmt.Printf("     GET    /api/media\n")
	fmt.Printf("     GET    /api/media/{id}\n")
	fmt.Printf("     DELETE /api/media/{id}\n")
	fmt.Printf("     PATCH  /api/media/{id}\n")
	fmt.Printf("     GET    /api/stats\n\n")

	if srvErr := http.ListenAndServe(addr, mux); srvErr != nil {
		fmt.Fprintf(os.Stderr, "❌ Server error: %v\n", srvErr)
	}
}

// corsWrap adds CORS headers so the HTML report can call the API from file:// or another port.
func corsWrap(handler http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PATCH, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		handler(w, r)
	}
}

func handleListMedia(w http.ResponseWriter, r *http.Request, database *db.DB) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	items, err := database.ListMedia(0, 10000)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, items)
}

func handleMediaByID(w http.ResponseWriter, r *http.Request, database *db.DB) {
	idStr := strings.TrimPrefix(r.URL.Path, "/api/media/")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		http.Error(w, "invalid id", http.StatusBadRequest)
		return
	}

	switch r.Method {
	case http.MethodGet:
		m, getErr := database.GetMediaByID(id)
		if getErr != nil {
			http.Error(w, "not found", http.StatusNotFound)
			return
		}
		writeJSON(w, m)

	case http.MethodDelete:
		if delErr := database.DeleteMedia(id); delErr != nil {
			http.Error(w, delErr.Error(), http.StatusInternalServerError)
			return
		}
		writeJSON(w, map[string]string{"status": "deleted"})

	case http.MethodPatch:
		var updates map[string]interface{}
		if decErr := json.NewDecoder(r.Body).Decode(&updates); decErr != nil {
			http.Error(w, "invalid json", http.StatusBadRequest)
			return
		}
		// For now, support updating basic fields via direct SQL
		for key, val := range updates {
			switch key {
			case "title", "genre", "director", "description", "tagline":
				database.Exec("UPDATE media SET "+key+" = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?", val, id)
			}
		}
		m, _ := database.GetMediaByID(id)
		writeJSON(w, m)

	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func handleStats(w http.ResponseWriter, r *http.Request, database *db.DB) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	total, _ := database.CountMedia("")
	movies, _ := database.CountMedia("movie")
	tv, _ := database.CountMedia("tv")
	writeJSON(w, map[string]int{"total": total, "movies": movies, "tv_shows": tv})
}

func writeJSON(w http.ResponseWriter, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(data)
}
